### ISSUE TITLE
Could not createNamedContainerProperOrder / Error exists in the bytecode

### ISSUE THREAD

**Issue by abeggchr** [nebula-plugins/nebula-project-plugin#13]
I get the exception "Could not create an instance of type nebula.core.NamedContainerProperOrder_Decorated" when using the following build.gradle file.

Deleting the whole .gradle/cache and re-downloading the dependencies did not help.

----------- build.gradle
buildscript {
  repositories {    jcenter()  }
  dependencies {    classpath "com.netflix.nebula:nebula-project-plugin:2.0.0"  }
}

apply plugin: "nebula-facet"

facets {    performanceTest }

------------ Exception with Gradle 2.1 
- Exception is:
  org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'myTest'.
      at ...
  Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'nebula-facet']   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:117)
      at ...
  Caused by: org.gradle.api.GradleException: Could not generate a proxy class forclass nebula.core.NamedContainerProperOrder.
     at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:194)
      at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:60)
      at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
      at nebula.plugin.responsible.NebulaFacetPlugin.container(NebulaFacetPlugin.groovy:119)
      at nebula.plugin.responsible.NebulaFacetPlugin$container.callCurrent(Unknown Source)
      at nebula.plugin.responsible.NebulaFacetPlugin.apply(NebulaFacetPlugin.groovy:30)
      at nebula.plugin.responsible.NebulaFacetPlugin.apply(NebulaFacetPlugin.groovy)
      at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
      at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
      at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
      at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfiguratioAction.java:115)
      ... 40 more
  Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch

Exception Details:
  Location:
    nebula/core/NamedContainerProperOrder.<init>(Ljava/lang/Class;Lorg/gradle/in
ternal/reflect/Instantiator;Lgroovy/lang/Closure;)V @125: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 173a 0406 bd00 2859 032b 5359 042c
     ....

**Comment by greg7gkb** [comment]
I encountered this issue while trying to build the [RxJava project](https://github.com/ReactiveX/RxJava/).  Am using Gradle 2.2.1, JDK 1.7.0_71, and Mac OSX 10.10.1 (Yosemite).  To resolve, I've been trying to downgrade my jdk to 1.7.0_60 as suggested, however this triggers another bug on install caused by the OSX version number being [improperly parsed by the installer](https://bugs.openjdk.java.net/browse/JDK-8027686).

Not sure how to work around this now...

*Copy of error output, snipped:*
Exception Details:
  Location:
    nebula/core/NamedContainerProperOrder.<init>(Ljava/lang/Class;Lorg/gradle/internal/reflect/Instantiator;Lgroovy/lang/Closure;)V @125: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 173a 0406 bd00 2859 032b 5359 042c

**Comment by rspieldenner** [comment]
try JDK 1.7.0_72

**Comment by greg7gkb** [comment]
Gah - finally.  Thanks for the assist.

**Comment by kukgini** [comment]
I think to change micro version of JDK for avoiding build issue is not a clean solution. it should be re-opened.

**Comment by bmuschko** [comment]
@kukgini What version of Gradle and what version of the plugin are you using?

**Comment by rspieldenner** [comment]
I'm pretty sure it is a bug in groovy interop with java from 1.7.0_60-1.7.0_71 and also a range of 1.8 JDKs . I don't know of a good way around that besides being on a version that doesn't break groovy.

**Comment by kukgini** [comment]
gradle version : 2.2.1
nebula.netflixoss plugin version : 2.2.7

**Comment by kukgini** [comment]
In my environment, i can't handle java version. it's from our client side.
But, I can handle grade version (in minor versions). so, i upgraded grade version 2.2.1 -> 2.3.
And i got this:

./gradlew build
Inferred version: 2.0.0-SNAPSHOT

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/MX100/Users/soomin/D/2015/netflix/ribbonV2/ribbon/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':ribbon'.
> Failed to apply plugin [id 'nebula-facet']
   > Could not generate a proxy class for class nebula.core.NamedContainerProperOrder.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by srikanth-potana** [comment]
It also works fine with following configuration
------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_76 (Oracle Corporation 24.76-b04)
OS:           Windows 7 6.1 amd64

**Comment by hthetiot** [comment]
Fail with same error with following JAVA JDK version
- 1.7.0_67, 1.7.0_71, 1.7.0_79

Works fine with following version:
- 1.7.0_25, 1.7.0_45
