### ISSUE TITLE
SourceJarPlugin uses deprecated configureDocumentationVariantWithArtifact API

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/nebula-project-plugin#78]
```
Internal API configureDocumentationVariantWithArtifact (no FileResolver) has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use configureDocumentationVariantWithArtifact (with FileResolver) instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.4-rc-1/userguide/upgrading_version_7.html#lazypublishartifact_fileresolver
        at org.gradle.api.plugins.internal.JvmPluginsHelper.configureDocumentationVariantWithArtifact(JvmPluginsHelper.java:195)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at nebula.plugin.publishing.publications.SourceJarPlugin$_apply_closure1.doCall(SourceJarPlugin.groovy:50)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:72)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.api.internal.collections.CollectionFilter$1.execute(CollectionFilter.java:59)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:161)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:203)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:209)
        at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
        at nebula.plugin.publishing.publications.SourceJarPlugin.apply(SourceJarPlugin.groovy:43)
        at nebula.plugin.publishing.publications.SourceJarPlugin.apply(SourceJarPlugin.groovy)
```

**Comment by rpalcolea** [comment]
just need to upgrade publishing plugin. Took care of it https://github.com/nebula-plugins/nebula-publishing-plugin/releases/tag/v18.2.0 

Also, note to move to a public API :D

**Comment by rpalcolea** [comment]
addressed in https://github.com/nebula-plugins/nebula-project-plugin/pull/79
